version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: rss2newsletters_django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src 
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A rss2newsletters worker -l INFO --pool=solo 
    volumes:
      - .:/src
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A rss2newsletters beat -l INFO
    volumes:
      - .:/src
    depends_on:
      - web
      - redis
  redis:
    image: "redis:alpine"
