version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build: .
    container_name: rss2newsletters_django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src 
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A rss2newsletters worker -l INFO --pool=solo 
    volumes:
      - .:/src
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A rss2newsletters beat -l INFO
    volumes:
      - .:/src
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  redis:
    image: "redis:alpine"
