# Generated by Django 3.2.14 on 2022-07-19 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('feed_encoding', models.CharField(max_length=150)),
                ('last_sent', models.DateTimeField(blank=True)),
                ('subscriptions', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
