# Generated by Django 3.2.14 on 2022-07-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0003_alter_subscriber_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_encoding',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
