# Generated by Django 3.2.14 on 2022-07-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0004_alter_feed_feed_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_encoding',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
