# Generated by Django 3.2.14 on 2022-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0006_alter_feed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=150, unique=True),
        ),
    ]
