# Generated by Django 3.2.14 on 2022-07-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0007_alter_feed_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
