# Generated by Django 3.2.14 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0008_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
