# Generated by Django 3.2.14 on 2022-07-28 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedaggregator', '0009_feed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=150, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedaggregator.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', through='feedaggregator.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
