# Generated by Django 3.2.14 on 2022-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0010_auto_20220728_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='abbreviated',
            field=models.BooleanField(default=True),
        ),
    ]
