# Generated by Django 3.2.14 on 2022-07-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0011_feed_abbreviated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='abbreviated',
        ),
        migrations.AddField(
            model_name='feed',
            name='content_key',
            field=models.CharField(default='invalid', max_length=25),
        ),
    ]
