# Generated by Django 3.2.14 on 2022-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0012_auto_20220730_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='sorted_normal',
            field=models.BooleanField(default=True),
        ),
    ]
