# Generated by Django 3.2.15 on 2022-08-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0013_feed_sorted_normal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-date_subscribed']},
        ),
    ]
