# Generated by Django 3.2.15 on 2022-08-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0014_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['date_subscribed']},
        ),
    ]
