# Generated by Django 3.2.15 on 2022-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0016_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
