# Generated by Django 3.2.15 on 2022-08-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0017_entry_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['title']},
        ),
    ]
