# Generated by Django 3.2.15 on 2022-08-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0018_alter_feed_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
