# Generated by Django 3.2.15 on 2022-08-31 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0019_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'entries'},
        ),
    ]
