# Generated by Django 3.2.15 on 2022-10-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0021_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
