# Generated by Django 3.2.15 on 2022-10-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0022_entry_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='subscriptions',
        ),
    ]
