# Generated by Django 3.2.15 on 2022-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0023_auto_20221004_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
