# Generated by Django 3.2.15 on 2022-10-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0024_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='num_subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
