# Generated by Django 3.2.15 on 2022-10-10 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedaggregator', '0025_feed_num_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-num_subscribers']},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_time', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedaggregator.entry')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_time'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_entries', through='feedaggregator.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
