# Generated by Django 3.2.16 on 2022-11-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0026_auto_20221010_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
