# Generated by Django 3.2.16 on 2022-11-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0027_alter_subscription_date_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
