# Generated by Django 3.2.16 on 2022-12-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedaggregator', '0029_auto_20221201_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.ManyToManyField(related_name='feeds', to='feedaggregator.Category'),
        ),
    ]
